FROM php:8.3-fpm-alpine AS runtime

RUN apk add --no-cache nginx supervisor

WORKDIR /var/www

COPY backend/public/ /var/www/backend/public/

COPY docker/nginx-backend.conf /etc/nginx/nginx.conf
COPY docker/supervisord.conf /etc/supervisord.conf

EXPOSE 8080

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
